# Setup title
set -g set-titles on
set -g set-titles-string "$TERMINAL #T"

# Setup shell
set -g default-command "/bin/zsh"

# Setup terminal
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-termite:Tc"
#set -as terminal-overrides ',xterm*:sitm=\E[3m'

# Change prefix to C-q
unbind C-b
set-option -g prefix C-q
bind-key C-q send-prefix

# Split pane
bind h split-window -h -c "#{pane_current_path}"
bind v split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Switch pane
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# Enable mouse
set -g mouse on

# Vi like copy mode
set -g mode-keys vi

set-option -g allow-rename off

set-option -sg escape-time 10

# Theme
run-shell "~/.config/tmux/nord-tmux/nord.tmux"
