call plug#begin('~/.vim/plugged')
Plug 'octol/vim-cpp-enhanced-highlight'
Plug 'lucHermitte/vimfold4c'
Plug 'LucHermitte/lh-vim-lib'

Plug 'plasticboy/vim-markdown'
Plug 'iamcco/markdown-preview.vim'

function! BuildYCM(info)
      " info is a dictionary with 3 fields
      " - name:   name of the plugin
      " - status: 'installed', 'updated', or 'unchanged'
      " - force:  set on PlugInstall! or PlugUpdate!
      if a:info.status == 'installed' || a:info.force
        !python3 install.py --clang-completer
      endif
  endfunction     
Plug 'valloric/youcompleteme', {'do': function('BuildYCM')}
Plug 'scrooloose/syntastic'

Plug 'scrooloose/nerdtree'
Plug 'vim-airline/vim-airline'
Plug 'majutsushi/tagbar'
call plug#end()

" be iMproved required
set nocompatible

" Enables syntax highlighting by default.
syntax on

" Enable lines number
set number

" If using a dark background within the editing area and syntax highlighting
" turn on this option as well
set background=dark

" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
if has("autocmd")
  filetype plugin indent on
endif

"filetype off

" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
set showcmd     " Show (partial) command in status line.
set showmatch       " Show matching brackets.
set ignorecase      " Do case insensitive matching
set smartcase       " Do smart case matching
set incsearch       " Incremental search
set autowrite       " Automatically save before commands like :next and :make
set hidden      " Hide buffers when they are abandoned
set mouse=a     " Enable mouse usage (all modes)
set autoindent
set tabstop=4
set shiftwidth=4
set expandtab       " Use space instead of tab (\t)
autocmd FileType yaml setlocal ts =2 sts=2 sw=2 expandtab
set foldmethod=syntax

set list listchars=tab:»\ ,trail:.


" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

let g:fold_options = {
   \ 'fallback_method' : { 'line_threshold' : 2000, 'method' : 'syntax' },
   \ 'fold_blank': 0,
   \ 'fold_includes': 1,
   \ 'max_foldline_length': 'win',
   \ 'merge_comments' : 0,
   \ 'show_if_and_else': 1,
   \ 'strip_namespaces': 1,
   \ 'strip_template_arguments': 1
   \ }

" vim-markdown
let vim_markdown_folding_disabled = 1

" NerdTree
map <C-n> :NERDTreeToggle<CR>

" YouCompleteMe
let g:ycm_confirm_extra_conf = 1
let g:ycm_global_ycm_extra_conf = '~/.vim/ycm_extra_conf.py'
let g:ycm_python_binary_path = 'python3'

nnoremap <leader>yj :YcmCompleter GoToDefinitionElseDeclaration<CR>
nnoremap <leader>yg :YcmCompleter GoTo<CR>
nnoremap <leader>yi :YcmCompleter GoToImplementationElseDeclaration<CR>
nnoremap <leader>yd :YcmCompleter GetDoc<CR>
nnoremap <leader>ys :YcmDiags<CR>
nnoremap <F5> :YcmForceCompileAndDiagnostics<CR>

" let g:ycm_filetype_whitelist = { '*': 1 }
let g:ycm_key_invoke_completion = '<C-Space>'

let g:ycm_rsy_src_path = ''
